config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  mount ShopifyApp::Engine, at: '/'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  mount Sidekiq::Web => "/sidekiq"
  
  get '/help/index'

  get '/reports/index'
  get '/reports/download', to: 'reports#download'

  get '/variants/export_csv'
  get '/variants/import_csv', to: 'variants#import_csv', as: 'variants_import_csv'
  post '/variants/update_csv_threshold', to: 'variants#update_csv_threshold'
  put '/variants/', to: 'variants#update'
  
  post '/shopify/products/create', to: 'shopify/products#create'
  post '/shopify/products/update', to: 'shopify/products#update'
  post '/shopify/products/delete', to: 'shopify/products#delete'
  
  post '/shopify/app/uninstalled', to: 'shopify/apps#uninstalled'

  resources :variants, :except => [:show, :edit]
  resources :shop_settings, :except => [:show, :edit]
  resources :emails, :except => [:show, :index, :edit, :update]

  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop_setting.rb
class ShopSetting < ApplicationRecord
    
    belongs_to :shop
    
    has_many :emails
    accepts_nested_attributes_for :emails, allow_destroy: true, reject_if: proc { |att| att['email'].blank? }
    
    validates :global_threshold, numericality: { only_integer: true }, presence: true
    validates :alert_frequency, numericality: { only_integer: true }, presence: true
    validate :check_alert_frequency
    
    private

    def check_alert_frequency
        unless [1,6,12,24].include? self.alert_frequency
            errors.add(:alert_frequency, "Must be specified frequency value")
        end
    end
end

app/controllers/shop_settings_controller.rb
class ShopSettingsController < ApplicationController
  layout 'application'
  before_action :set_shop_setting, only: [:edit, :update]
  
  def index
    if current_shop.shop_setting.present?
      @shop_setting = current_shop.shop_setting
      if !@shop_setting.emails.nil?
        @emails = @shop_setting.emails
      end
    else
      redirect_to new_shop_setting_path
    end
  end
  
  def new
    @shop_setting = ShopSetting.new
  end

  def create
    @shop_setting = ShopSetting.new(shop_setting_params)
    @shop_setting.shop_id = current_shop.id
    respond_to do |format|
      if @shop_setting.save
        format.html { redirect_to shop_settings_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @global_threshold = @shop_setting.global_threshold
    @email_params = shop_setting_params[:emails_attributes]
    shop_setting_update_error_message = "Something went wrong.Please enter proper values and try again!"
    shop_setting_update_success_message = "Record successfully updated!"
    if shop_setting_params[:emails_attributes].present?
      @email_to_update = Email.find(shop_setting_params[:emails_attributes][:id])
      @email_id_to_update_for_error = @email_to_update.email
      @email_id = shop_setting_params[:emails_attributes][:id]
      @email = shop_setting_params[:emails_attributes][:email]
      @is_active = shop_setting_params[:emails_attributes][:is_active]
    end
    @shop_setting.update!(shop_setting_params)
    respond_to do |format|
      format.js { render "update.js.erb", :locals => {:shop_setting_update_error_message => shop_setting_update_error_message, :shop_setting_update_success_message => shop_setting_update_success_message} }
    end
  end

  private

    def set_shop_setting
      @shop_setting = ShopSetting.find(params[:id])
    end

    def shop_setting_params
      params.require(:shop_setting).permit(:global_threshold, :alert_frequency, emails_attributes: Email.attribute_names.map(&:to_sym))
    end
    
end

app/views/shop_settings/_form.html.erb
<%= stylesheet_link_tag "application", "button_style.css" ,:media => "all" %>
<%= stylesheet_link_tag "application", "form_style.css" ,:media => "all" %>
<%= stylesheet_link_tag "application", "table_style.css" ,:media => "all" %>

<div class="container text-center">
  <%= form_with(model: shop_setting, local: true, :html => {:id => "settingForm"},:class => "card_shadow") do |form| %>
    <% if shop_setting.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(shop_setting.errors.count, "error") %> prohibited this shop_setting from being saved:</h2>
        <ul>
          <% shop_setting.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <label style="float:left";>Global Threshold:</label>
      <%= form.number_field :global_threshold,:class => "form-control", data: {toggle: "tooltip"}, title: "Please enter positive integer value." %>
    </div>
    <div class="form-group">
      <label style="float:left";>Alert Frequency:</label>
      <br>
      <%= form.select :alert_frequency, [["1 min", 1],["6 hrs", 6],["12 hrs", 12],["24 hrs",24]] ,{},{:class => "form-control"} %>
    </div>
    <br>
    <div class="form-actions">
      <%= form.button :Submit , :class => 'btn submit_btn' %> 
    </div> 
  <% end %>
</div>

app/views/shop_settings/index.html.erb
<%= stylesheet_link_tag "application", "table_style.css" ,:media => "all" %>
<%= stylesheet_link_tag "application", "button_style.css" ,:media => "all" %>
<%= stylesheet_link_tag "application", "toast_notification_style.css" ,:media => "all" %>  
<%= stylesheet_link_tag "application", "header_style.css" ,:media => "all" %> 
<div class="container text-center" style="margin-bottom:20">
  <p id="notice" style="color:green;text-align:left;"><%= notice %></p>
  <div class="container header-style">
    <div class="row">
      <div class="col">
        <h4><b>CONFIGURATION</b></h4>
      </div>
    </div>
  </div>
  <br>
  <div id="snackbar-error">
  </div>
  <div id="snackbar-success">
  </div>
  <div class="table-responsive">
    <table id ="configuration-table" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Global Threshold</th>
          <th>Alert Frequency</th>
          <th>Edit</th>
        </tr>
      </thead>

      <tbody>
        <%if !@shop_setting.nil?%>
          <tr>
            <td id=<%=@shop_setting.id%>><%= @shop_setting.global_threshold %></td>
            <% if @shop_setting.alert_frequency == 1%>
              <td id=<%=(@shop_setting.shop_id)+5%>><%= @shop_setting.alert_frequency%> min </td>
            <% else %>
              <td id=<%=(@shop_setting.shop_id)+5%>><%= @shop_setting.alert_frequency%> hrs </td>
            <% end %>
            <td><i class="fa fa-pencil-square-o" aria-hidden="true" style="font-size:20px;" onclick="editclicked(this);"></i></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>

  <br>
  <div class="container header-style">
    <div class="row">
      <div class="col">
        <h4><b>EMAILS</b></h4>
      </div>
      <div class="col">
        <%= link_to 'Add Email', new_email_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn editbtn'}  %>
      </div>
    </div>
  </div>
  <br>
  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
  <div class="table-responsive">
    <table id="emails-table" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Email</th>
          <th>Is Active</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      
      <tbody>
        <%if !@emails.nil?%>
          <% @emails.each do |email|%>
            <tr>
              <td><%= email.email %></td>
              <input type="hidden" id=<%=@shop_setting.id%>>
              <td><%= email.is_active %></td>
              <td><i class="fa fa-pencil-square-o" aria-hidden="true" data-email_id=<%=email.id%> style="font-size:20px;" onclick="editclick(this);"></i></td>
              <td><i class="fa fa-times" aria-hidden="true" data-email_id_delete=<%=email.id%> style="font-size:20px;color:red;" onclick="deleteclick(this);"></i></td> 
              <input type="hidden" id=<%=@shop_setting.id%>>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shop_settings/new.html.erb
<div class="container text-center">
    <h3>Create Configuration</h3>
</div>
<%= render 'form', shop_setting: @shop_setting %>

app/views/shop_settings/update.js.erb
var globalThreshold = document.getElementById(<%=@shop_setting.id%>);
var globalthresholdTd = $(globalThreshold).closest('td');
var alertFrequency = document.getElementById(<%=(@shop_setting.shop_id)+5%>);
var alertFrequencyTd = $(alertFrequency).closest('td');
var table = document.getElementById('configuration-table');
var editIconTdEle = table.rows[1].cells[2];

<%if @email_params.present?%>
    var updateiconElem = $('[data-email_id*= '+<%=@email_id%>+']');
    var prevTdElem = $(updateiconElem).closest('td'); 
    var updatedIsActiveTd = $(prevTdElem).prev();
    var hiddenField = $(updatedIsActiveTd).prev();
    var updatedemailTd = $(hiddenField).prev();
<%end%>

<% if @shop_setting.errors.present? %>

    var divElementforError = document.getElementById("snackbar-error");
    divElementforError.innerHTML = "<%= shop_setting_update_error_message %>"
    divElementforError.className = "show";
    setTimeout(function(){ divElementforError.className = divElementforError.className.replace("show", ""); }, 3000);
    
    $(globalthresholdTd).replaceWith(function () {
        return `<td id=<%=@shop_setting.id%>><%= @global_threshold %></td>`;
    });

    <% if @shop_setting.alert_frequency == 1%>
        $(alertFrequencyTd).replaceWith(function () {
            return `<td id=<%=(@shop_setting.shop_id)+5%>><%= @shop_setting.alert_frequency %> min</td>`;
        });
    <% else %>
        $(alertFrequencyTd).replaceWith(function () {
            return `<td id=<%=(@shop_setting.shop_id)+5%>><%= @shop_setting.alert_frequency %> hrs</td>`;
        });
    <% end %> 
    
    $(editIconTdEle).replaceWith(function () {
        return `<td><i class="fa fa-pencil-square-o" aria-hidden="true" style="font-size:20px;" onclick="editclicked(this);"></i></td>`;
    });

    <%if @email_params.present?%>

        $(updateiconElem).replaceWith(function () {
            return `<i class="fa fa-pencil-square-o" aria-hidden="true" data-email_id=<%=@email_id%> style="font-size:20px;" onclick="editclick(this);"></i>`;
        });

        $(updatedIsActiveTd).replaceWith(function () {
            return `<td><%=@is_active %></td>`;
        });

        <% if @email.present? %>
            $(updatedemailTd).replaceWith(function () {
            return ` <td><%=@email%></td>`;
        });
        <% else %>    
            $(updatedemailTd).replaceWith(function () {
            return ` <td><%=@email_id_to_update_for_error%></td>`;
        });
        <% end %>

    <%end%>

<% else %>

    var divElementforsuccess = document.getElementById("snackbar-success");
    divElementforsuccess.innerHTML = "<%= shop_setting_update_success_message %>"
    divElementforsuccess.className = "show";
    setTimeout(function(){ divElementforsuccess.className = divElementforsuccess.className.replace("show", ""); }, 3000);
    
    $(globalthresholdTd).replaceWith(function () {
        return `<td id=<%=@shop_setting.id%>><%= @shop_setting.global_threshold %></td>`;
    });

    <% if @shop_setting.alert_frequency == 1%>
        $(alertFrequencyTd).replaceWith(function () {
            return `<td id=<%=(@shop_setting.shop_id)+5%>><%= @shop_setting.alert_frequency %> min</td>`;
        });
    <% else %>
        $(alertFrequencyTd).replaceWith(function () {
            return `<td id=<%=(@shop_setting.shop_id)+5%>><%= @shop_setting.alert_frequency %> hrs</td>`;
        });
    <% end %> 
    
    $(editIconTdEle).replaceWith(function () {
        return ` <td><i class="fa fa-pencil-square-o" aria-hidden="true" style="font-size:20px;" onclick="editclicked(this);"></i></td>`;
    });  

    <%if @email_params.present?%>

        $(prevTdElem).replaceWith(function () {
            return `<td><i class="fa fa-pencil-square-o" aria-hidden="true" data-email_id=<%=@email_id%> style="font-size:20px;" onclick="editclick(this);"></i></td>`;
        });

        $(updatedIsActiveTd).replaceWith(function () {
            return `<td><%=@is_active %></td>`;
        });
        <% if @email.present? %>
            $(updatedemailTd).replaceWith(function () {
            return ` <td><%=@email%></td>`;
        });
        <% else %>    
            $(updatedemailTd).replaceWith(function () {
            return ` <td><%=@email_id_to_update_for_error%></td>`;
        });
        <% end %>

    <% end %>
    
<% end %>