config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  mount ShopifyApp::Engine, at: '/'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  mount Sidekiq::Web => "/sidekiq"
  
  get '/help/index'

  get '/reports/index'
  get '/reports/download', to: 'reports#download'

  get '/variants/export_csv'
  get '/variants/import_csv', to: 'variants#import_csv', as: 'variants_import_csv'
  post '/variants/update_csv_threshold', to: 'variants#update_csv_threshold'
  put '/variants/', to: 'variants#update'
  
  post '/shopify/products/create', to: 'shopify/products#create'
  post '/shopify/products/update', to: 'shopify/products#update'
  post '/shopify/products/delete', to: 'shopify/products#delete'
  
  post '/shopify/app/uninstalled', to: 'shopify/apps#uninstalled'

  resources :variants, :except => [:show, :edit]
  resources :shop_settings, :except => [:show, :edit]
  resources :emails, :except => [:show, :index, :edit, :update]

  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/variant.rb
class Variant < ApplicationRecord
    
    belongs_to :product
    belongs_to :shop
    
    validates :quantity, numericality: { only_integer: true }, presence: true
    validates :shopify_variant_id, presence: true, uniqueness: true
    validates :local_threshold, numericality: { only_integer: true, greater_than_or_equal_to: 0}, presence: true, allow_nil: true
    validates :inventory_management, presence: true, allow_nil: true
    
    def threshold
        ActiveRecord::Base.connection.exec_query(
            "SELECT threshold(#{self.local_threshold || "null"}, #{self.shop.shop_setting.global_threshold})"
        ).rows.flatten.first
    end

    def self.write_variants_from_shopify_products_json shop_id:, shopify_products_json:
        ActiveRecord::Base.connection.execute(
            <<-SQL
                BEGIN TRANSACTION;
                
                INSERT INTO variants (shop_id, product_id, shopify_variant_id, sku, quantity, inventory_management, created_at, updated_at)
                SELECT 
                    #{shop_id} AS shop_id, 
                    (SELECT id FROM products WHERE products.shopify_product_id = variants_json.shopify_product_id LIMIT 1) AS product_id, 
                    shopify_variant_id, sku, quantity, inventory_management, created_at, updated_at 
                FROM
                (
                    SELECT
                        (json_array_elements(products_json -> 'variants') ->> 'id')::BIGINT AS shopify_variant_id,
                        (json_array_elements(products_json -> 'variants') ->> 'product_id')::BIGINT AS shopify_product_id,
                        json_array_elements(products_json -> 'variants') ->> 'sku' AS sku,
                        (json_array_elements(products_json -> 'variants') ->> 'inventory_quantity')::INTEGER AS quantity,
                        json_array_elements(products_json -> 'variants') ->> 'inventory_management' AS inventory_management,
                        timezone('utc', now()) AS created_at,
                        timezone('utc', now()) AS updated_at
                    FROM json_array_elements(
                    $$
                    #{shopify_products_json}
                    $$::json) AS products_json
                ) AS variants_json;

                COMMIT TRANSACTION;
            SQL
        )
    end

    # Certain versions of excel changes format of big numbers. Eg: 32274860376127 to 3227+e1
    # Prepending shopify_variant_id and sku with # converts it to text and preserves the number
    # Since this method is used ONLY to export products to csv, this change has been made
    def self.export_variants_data_to_csv shop_id:
        ActiveRecord::Base.connection.execute(
            <<-SQL
                SELECT  
                    CONCAT('#', variants.shopify_variant_id) AS id, 
                    products.title AS title, 
                    CONCAT('#', variants.sku) AS sku, 
                    variants.quantity AS quantity, 
                    COALESCE(variants.local_threshold, shop_settings.global_threshold) AS threshold
                FROM variants
                INNER JOIN products ON variants.product_id = products.id 
                INNER JOIN shops ON products.shop_id = shops.id
                INNER JOIN shop_settings ON shop_settings.shop_id = shops.id
                WHERE products.shop_id = #{shop_id}
                AND products.status = 'active'
                AND variants.inventory_management IS NOT NULL;
            SQL
        )
    end

    def self.update_local_threshold_from_csv shop_id:, csv_json:
        ActiveRecord::Base.connection.execute(
            <<-SQL
                BEGIN TRANSACTION;
                
                WITH variants_csv_table AS (
                    SELECT 
                        TRIM(LEADING '#' FROM variants_csv."Variant ID")::BIGINT as shopify_variant_id,
                        (variants_csv."Threshold")::INT AS threshold
                    FROM json_populate_recordset(
                        null::record,
                        $$
                        #{csv_json}
                        $$
                    ) AS variants_csv
                    (
                        "Variant ID" TEXT,
                        "Threshold" TEXT
                    )
                )
                
                UPDATE variants
                SET local_threshold = (
                    CASE 
                        WHEN variants_csv_table.threshold = (SELECT global_threshold FROM shop_settings WHERE shop_settings.shop_id=#{shop_id} LIMIT 1)
                        THEN NULL
                        ELSE variants_csv_table.threshold
                    END),
                    updated_at = timezone('utc', now())
                FROM variants_csv_table
                WHERE variants.shopify_variant_id = variants_csv_table.shopify_variant_id;
                
                COMMIT TRANSACTION;
            SQL
        )
    end

    def self.get_low_inventory_variants shop_id:
        ActiveRecord::Base.connection.execute(
            <<-SQL
                SELECT
                    STRING_AGG (
                        CONCAT('#', shopify_variant_id) 
                        || ',' || 
                        REPLACE(REPLACE(title, ',', ' '), '\n', ' ')
                        || ',' || 
                        CONCAT('#', sku) 
                        || ',' || 
                        quantity 
                        || ',' || 
                        threshold,
                        '\n'
                    ) 
                AS variants_csv
                FROM (
                    SELECT 
                    CASE WHEN variants.quantity <= threshold(variants.local_threshold, shop_settings.global_threshold) THEN variants.shopify_variant_id END AS shopify_variant_id,
                    CASE WHEN variants.quantity <= threshold(variants.local_threshold, shop_settings.global_threshold) THEN products.title END AS title,
                    CASE WHEN variants.quantity <= threshold(variants.local_threshold, shop_settings.global_threshold) THEN variants.sku END AS sku,
                    CASE WHEN variants.quantity <= threshold(variants.local_threshold, shop_settings.global_threshold) THEN variants.quantity END AS quantity,
                    CASE WHEN variants.quantity <= threshold(variants.local_threshold, shop_settings.global_threshold) THEN threshold(variants.local_threshold, shop_settings.global_threshold) END AS threshold
                    
                    FROM variants
                    INNER JOIN products ON variants.product_id = products.id
                    INNER JOIN shop_settings ON shop_settings.shop_id = #{shop_id}
                    WHERE variants.shop_id = #{shop_id} 
                    AND variants.inventory_management IS NOT NULL
                    AND products.status = 'active'
                    ) AS low_inventory_stocks
                WHERE shopify_variant_id IS NOT NULL;
            SQL
        )
    end
        
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  
  before_action :set_variant, only: [:update]
  before_action :shop_setting_created?
  
  def index
    if !current_shop.sync_complete
      flash.now[:notice] = "Products are still being synced to the application. We will notify you via email once it is completed."
    else
      respond_to do |format|
        format.html
        format.json { render json: VariantDatatable.new(params, shop: current_shop) }
      end
    end
  end

  def export_csv
    ExportCsvJob.perform_later(shop_id: current_shop.id)
    export_csv_success_message = "Please wait while the products are being emailed as a CSV file.This will take few minutes!"
    respond_to do |format|
      format.js { render "export_csv.js.erb", :locals => {:export_csv_success_message => export_csv_success_message} }
    end 
  end

  def import_csv
  end

  def update_csv_threshold
    @import_csv_successful = ImportCsvService.new(shop_id: current_shop.id, file_path: params[:file].path).execute
    import_csv_success_message = "Variants Threshold successfully updated!"
    import_csv_error_message = "There was an error updating Variants Threshold. Please refer to the csv file format on the Home page."
    respond_to do |format|
      format.js { render "update_csv_threshold.js.erb", :locals => {:import_csv_success_message => import_csv_success_message, :import_csv_error_message => import_csv_error_message} }
    end
  end

  def update
    global_threshold = current_shop.shop_setting.global_threshold
    @current_variant_threshold = @variant.threshold
    update_threshold_success_message = "Threshold successfully updated!"
    update_threshold_error_message = "Please enter a valid integer value to update!"
    if !(global_threshold == (params[:variant][:local_threshold].to_i))
      @variant.update(variant_params)
    else
      @variant.update(local_threshold: nil)
    end
    respond_to do |format|
      format.js { render "update.js.erb", :locals => {:update_threshold_success_message => update_threshold_success_message, :update_threshold_error_message => update_threshold_error_message} }
    end   
  end

  private

  def set_variant
    @variant = Variant.find(params[:id])
  end

  def variant_params
    params.require(:variant).permit(:local_threshold)
  end

end

app/views/variants/_variants_import_csv.html.erb
<div class="modal-header" style="color:black">
  <h4 class="modal-title" style="font-family: varela;" id="myModalLabel"><b>Upload File</b></h4>
  <button type="button" style="color: #000000;" class="close" data-dismiss="modal">x</button>
</div>
<%= form_tag( { :action => 'update_csv_threshold' },:remote => true, :multipart => true) %>
  <br/>
  <h6>Please click on choose file or drag and drop file here.</h6>
  <div class="file-upload-wrapper">
    <input type="file" id="input-file-now" class="file-upload choose_file_btn" style="width:300px;height:100px;" name="file" />
  </div>
  <br /><br />
  <div id="submit">
    <%= submit_tag( "Upload file" ,:class=>"upload_file_submit") %>
  </div>
<%# end %>

app/views/variants/export_csv.js.erb
var divElementforExportCsv = document.getElementById("snackbar-success");
divElementforExportCsv.innerHTML = "<%= export_csv_success_message %>"
divElementforExportCsv.className = "show";
setTimeout(function(){ divElementforExportCsv.className = divElementforExportCsv.className.replace("show", ""); }, 3000);
    

app/views/variants/import_csv.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'variants_import_csv') %>");
$("#modal-window").modal();

app/views/variants/index.html.erb
<%= stylesheet_link_tag "application", "button_style.css" ,:media => "all" %>
<%= stylesheet_link_tag "application", "table_style.css" ,:media => "all" %> 
<%= stylesheet_link_tag "application", "toast_notification_style.css" ,:media => "all" %> 
<%= stylesheet_link_tag "application", "header_style.css" ,:media => "all" %> 
<html>
  <body>
    <div class="container text-center" style="margin-bottom:20">
      <p id="notice"><%= notice %></p>
      <div id="snackbar-error">
      </div>
      <div id="snackbar-success">
      </div>
      <div class="container header-style">
        <div class="row">
          <div class="col">
            <h4><b>PRODUCTS</b></h4>
          </div>
          <div class="col">
            <%= link_to "Download CSV", variants_export_csv_path, remote: true, :class => "btn export-csv-btn"%>
            <%= link_to 'Upload CSV', variants_import_csv_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn import-csv-btn'} %>
          </div>
        </div>
      </div>
      <br>
      <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content"></div>
        </div>
      </div>
      <div class="table-responsive">
        <table id="variants-datatable" data-source="<%= variants_path(format: :json) %>" class="table table-bordered table-striped" >
          <thead>
            <tr>
              <th>Product Title</th> 
              <th>SKU</th>
              <th>Quantity</th>
              <th>Threshold</th>
              <th>Edit</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
      <br>      
    </div>
  </body>
</html>

app/views/variants/update.js.erb
<% if @variant.errors.present? %>
    var divElementforError = document.getElementById("snackbar-error");
    divElementforError.innerHTML = "<%= update_threshold_error_message %>"
    divElementforError.className = "show";
    setTimeout(function(){ divElementforError.className = divElementforError.className.replace("show", ""); }, 3000);
    var thresholdTr = document.getElementById(<%=@variant.id%>);
    var thresholdInputElem = $(thresholdTr).find('div');
    $(thresholdInputElem).replaceWith(function () {
        return `<td class="variant-threshold-text" onclick="updateIconPressed(this);"><%= @current_variant_threshold %></td>`;
    });
    $(thresholdTr).find('i').replaceWith(function () {
        return `<i class="fa fa-pencil-square-o" aria-hidden="true" style="font-size:20px;" onclick="editIconclicked(this);"></i>`;
    });
 
<% else %>

    var divElementforsuccess = document.getElementById("snackbar-success");
    divElementforsuccess.innerHTML = "<%= update_threshold_success_message %>"
    divElementforsuccess.className = "show";
    setTimeout(function(){ divElementforsuccess.className = divElementforsuccess.className.replace("show", ""); }, 3000);
    var thresholdTr = document.getElementById(<%=@variant.id%>);
    var thresholdInputElem = $(thresholdTr).find('div');
    $(thresholdInputElem).replaceWith(function () {
        return `<td class="variant-threshold-text" onclick="updateIconPressed(this);"><%= @variant.threshold %></td>`;
    });
    $(thresholdTr).find('i').replaceWith(function () {
        return `<i class="fa fa-pencil-square-o" aria-hidden="true" style="font-size:20px;" onclick="editIconclicked(this);"></i>`;
    });
    
<% end %>

app/views/variants/update_csv_threshold.js.erb
$('#modal-window').modal('hide');
<% if @import_csv_successful %>
    var divElementForImportCsvSuccess = document.getElementById("snackbar-success");
    divElementForImportCsvSuccess.innerHTML = "<%= import_csv_success_message %>"
    divElementForImportCsvSuccess.className = "show";
    setTimeout(function(){ divElementForImportCsvSuccess.className = divElementForImportCsvSuccess.className.replace("show", ""); }, 3000);
<% else %>
    var divElementforImportCsvError = document.getElementById("snackbar-error");
    divElementforImportCsvError.innerHTML = "<%= import_csv_error_message %>"
    divElementforImportCsvError.className = "show";
    setTimeout(function(){ divElementforImportCsvError.className = divElementforImportCsvError.className.replace("show", ""); }, 3000);
<% end %>