config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  mount ShopifyApp::Engine, at: '/'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  mount Sidekiq::Web => "/sidekiq"
  
  get '/help/index'

  get '/reports/index'
  get '/reports/download', to: 'reports#download'

  get '/variants/export_csv'
  get '/variants/import_csv', to: 'variants#import_csv', as: 'variants_import_csv'
  post '/variants/update_csv_threshold', to: 'variants#update_csv_threshold'
  put '/variants/', to: 'variants#update'
  
  post '/shopify/products/create', to: 'shopify/products#create'
  post '/shopify/products/update', to: 'shopify/products#update'
  post '/shopify/products/delete', to: 'shopify/products#delete'
  
  post '/shopify/app/uninstalled', to: 'shopify/apps#uninstalled'

  resources :variants, :except => [:show, :edit]
  resources :shop_settings, :except => [:show, :edit]
  resources :emails, :except => [:show, :index, :edit, :update]

  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
    
    belongs_to :shop

    validates :file_name, presence: true

    def file_url
        "https://#{ENV["DO_SPACE_NAME"]}.#{ENV["DO_SPACES_CDN_ENDPOINT"]}/lina/reports/#{self.shop_name}/#{self.file_name}"
    end
    
    def created_at
        attributes['created_at'].strftime("%d %b %Y  %H:%M:%S%p")
    end

    private

    def shop_name
        self.shop.shopify_domain.split(".myshopify.com")[0]
    end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :csv_params, only: %i[download]

  def index
    if current_shop.shop_setting.present?
      respond_to do |format|
        format.html
        format.json { render json: ReportDatatable.new(params, shop: current_shop, view_context: view_context) }
      end 
    else
      redirect_to new_shop_setting_path
    end
  end

  def download 
    @report = Report.find(params[:report_id])
    data = HTTParty.get(@report.file_url)
    send_data data.to_s, filename: @report.file_name, type: :csv, disposition: "attachment"
  end

  private

  def csv_params
    params.permit(:report_id)
  end

end

app/views/reports/_report.html.erb
<tr>
  <td><%= report.created_at %></td>
  <td><%= link_to '<i class="fa fa-download" aria-hidden="true"></i>'.html_safe, reports_download_path(report_id: report.id) %></td> 
</tr>

app/views/reports/index.html.erb
<%= stylesheet_link_tag "application", "table_style.css" ,:media => "all" %> 
<%= stylesheet_link_tag "application", "header_style.css" ,:media => "all" %> 
<div class="container">
  <div class="container header-style" style="margin-bottom:20px">
    <div class = "row">
      <div class="col">
        <h4><b>REPORTS LIST</b></h4>
      </div>
    </div>
  </div>
</div>
<div class="container text-center" style="margin-bottom:20">    
  <div class="table-responsive">
    <table id="reports-datatable" data-source="<%= reports_index_path(format: :json) %>" class="table table-bordered table-striped">
      <thead>
        <th>Created At</th>
        <th>Download</th>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
</div>