config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  mount ShopifyApp::Engine, at: '/'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end
  mount Sidekiq::Web => "/sidekiq"
  
  get '/help/index'

  get '/reports/index'
  get '/reports/download', to: 'reports#download'

  get '/variants/export_csv'
  get '/variants/import_csv', to: 'variants#import_csv', as: 'variants_import_csv'
  post '/variants/update_csv_threshold', to: 'variants#update_csv_threshold'
  put '/variants/', to: 'variants#update'
  
  post '/shopify/products/create', to: 'shopify/products#create'
  post '/shopify/products/update', to: 'shopify/products#update'
  post '/shopify/products/delete', to: 'shopify/products#delete'
  
  post '/shopify/app/uninstalled', to: 'shopify/apps#uninstalled'

  resources :variants, :except => [:show, :edit]
  resources :shop_settings, :except => [:show, :edit]
  resources :emails, :except => [:show, :index, :edit, :update]

  root :to => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
  <%= content_tag(:div, nil, id: 'shopify-app-flash', data: { flash: { notice: flash[:notice], error: flash[:error] } }) %>
<% end %>

app/views/layouts/_nav.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Home</title>
        
    </head>
    <body>
        <div class="top-bar navbar-default" oncontextmenu="return false;">
            <div class="container" oncontextmenu="return false;">
                <div class="row">
                    <div class="col-sm-4">
                        <a class="navbar-brand" href=<%=root_path%>><img src="https://s3.ap-south-1.amazonaws.com/referral-image-logo/logo.png" alt="" /></a>
                    </div>
                    <div class="col-sm-4">
                        <ul class="list-inline">
                            <li><i class="fa fa-envelope-o"></i> <a href="mailto:abhisarika.das@kloctechnologies.com(opens in new tab)?Subject=low-inventory-notification-app" target="_top"> shopifyexpert@kloctechnologies.com </a></li>
                        </ul>
                    </div>
                   <div class="col-sm-4 text-right">
                        <ul class="list-inline list-inline1">
                            <li><a href="https://twitter.com/klocsutra" target="_blank"><i class="fa fa-twitter"></i></a></li> &nbsp&nbsp
                            <li><a href="https://www.facebook.com/newklocsutra" target="_blank"><i class="fa fa-facebook" ></i></a></li> &nbsp&nbsp
                            <li><a href="https://www.instagram.com/klocsutra/" target="_blank"><i class="fa fa-instagram"></i></a></li> &nbsp&nbsp
                        </ul> 
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto navbar-right">
                    <li class="nav-item mr-2">
                        <%= link_to "Home",root_path ,:class => "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Products",variants_path,:class => "nav-link"  %> 
                    </li>
                     <li class="nav-item">
                        <%= link_to "Reports",reports_index_path, :class => "nav-link"  %> 
                    </li>
                    <li class="nav-item">
                        <%= link_to "Configuration",shop_settings_path,:class => "nav-link"  %> 
                    </li>
                    <li class="nav-item">
                        <%= link_to "Help",help_index_path, :class => "nav-link"  %> 
                    </li>
                </ul>
            </div>
        </div>
        <hr>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyKlocLowInventoryNotification</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> 
    <%= stylesheet_link_tag "application", "nav_style.css" ,:media => "all" %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" >
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
       <%= render "layouts/nav" %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application' %>
    <% if ShopifyApp.use_webpacker? %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% else %>
      <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <% end %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://unpkg.com/@shopify/app-bridge"></script>

    <%= content_tag(:div, nil, id: 'shopify-app-init', data: {
      api_key: ShopifyApp.configuration.api_key,
      shop_origin: @shop_origin || (@current_shopify_session.domain if @current_shopify_session),
      debug: Rails.env.development?
    } ) %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>